### PR TITLE
My Portfolio Project Deploy Using Github Pages

### PR DESCRIPTION
**Pull request by David-Kasilia**
### To Highlight

- Created application-deploy branch.
- Used the branches as the base to deploy the project.
- Ensured it worked properly on physical devices.
- Click the link below to view the live preview of the website: 
- https://david-kasilia.github.io/My-Portfolio-Microverse-Project/

### CODE REVIEW

**Comment by David-Kasilia** [comment]
> Hi @David-Kasilia ,
> 
>  [ ](https://camo.githubusercontent.com/b3b3ee6d758658d67942036c5b060d9d58f1952e1f78359bfee52eaa621eefbf/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966) 68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966 [ ](https://camo.githubusercontent.com/b3b3ee6d758658d67942036c5b060d9d58f1952e1f78359bfee52eaa621eefbf/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> ## Highlights
> 
>     * Nice Design 👍
> 
>     * No linter error 💯
> 
>     * Descriptive PR 👍
> 
> 
> ## Required Changes ♻️
> 
>     * [ ]  Please, kindly add the Live Demo link to your readme file to meet the project requirement.
> 
> 
> ## Optional suggestions
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Hello @zieeco . Kindly Review My README file because it already contains the link to my live demo
link
.

**Comment by David-Kasilia** [comment]
Hello @zieeco . Kindly Review My README file because it already contains the link to my live demo. Here is an image from my readme fil
link
e

**Review by nicupop729 — COMMENTED** [review]
Hello @David-Kasilia 👋,

_This is an additional review as a result of the second opinion request._

Nice implementation of the project requirements!
As I checked, you already have implemented in the project the requirements from this milestone. I am glad to say that you were right.

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as "approve" right away :)

Keep rocking 🚀!

**Comment by David-Kasilia** [comment]
> Hello @David-Kasilia 👋,
> 
> _This is an additional review as a result of the second opinion request._
> 
> Nice implementation of the project requirements! As I checked, you already have implemented in the project the requirements from this milestone. I am glad to say that you were right.
> 
> As this was the only reason that your project was not approved it will be approved as soon as possible. Please ask for another review in your Dashboard and the next Code Reviewer will mark it as "approve" right away :)
> 
> Keep rocking 🚀!

@nicupop729 👋 Hello too 😄 . Thank you for your quick response I appreciate your second opinion on your review. Thank you very much 😃

**Pull request merged**
